### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by diogovalada** [quantumsim/qsoverlay#16]
I followed the installation instructions, but here's what happens when I try to `import qsoverlay`:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\qsoverlay\qsoverlay\__init__.py", line 1, in <module>
    from .circuit_builder import Builder
  File "C:\Users\user\qsoverlay\qsoverlay\circuit_builder.py", line 10, in <module>
    import quantumsim.circuit
ModuleNotFoundError: No module named 'quantumsim.circuit'
```

**Comment by slavoutich** [comment]
Installation instructions are a bit outdated, sorry for that. You may install quantumsim either from PyPi (`pip install --upgrade quantumsim`) or check out the branch `stable/v0.2` (`pip install --upgrade https://gitlab.com/quantumsim/quantumsim.git@stable/v0.2`). `master` branch is a WIP of release 1.0, which has broken reverse compatibility, but will bring many improvements.

Meanwhile this issue should remain open, until we update installation instructions.
